import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./StoreProvider";
import ThemeProviderWrapper from "./ThemeProvider";
import Navbar from "@/components/Header/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProviderWrapper>
          <StoreProvider>
            <Navbar />
            <div className="flex">
              <div className="w-8/12">
                {children}
              </div>
              <div className="w-4/12">
                <Sidebar/>
              </div>
            </div>
          </StoreProvider>
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
